name: Build and deploy Docker app to Azure
on:
  push:
    branches:
      - master

env:
  APPNAME: javascript4test-anand
  APPLICATIONPATH: Application
  HOSTINGPLAN: javascript4test-anand
  DOCKERFILEPATH: "Application"
  REGISTRYSKU: "Standard"
  REGISTRYNAME: "javascript4testanandacr"
  REGISTRYLOCATION: "South Central US"
  IMAGENAME: "javascript4testanandc093"
  RESOURCEGROUPNAME: javascript4test-anand-rg
  LOCATION: South Central US
  APPINSIGHTSLOCATION: South Central US
  SUBSCRIPTIONID: 7489b9b9-8abe-4b02-a0d9-f09f368df55f
  SKU: S1 Standard
  JAVA_VERSION: 1.8

jobs:
  build:
    name: Build and push Application to ACR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn -B package --file $GITHUB_WORKSPACE/${{env.DOCKERFILEPATH}}/pom.xml
    - name: copy scripts directory
      run: cp -r $GITHUB_WORKSPACE/Application/sampleWebApp.FunctionalTests/scripts $GITHUB_WORKSPACE/Application/sampleWebApp.FunctionalTests/target
    - name: Upload target to test artifacts
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: testartifacts      
        path: ./Application/sampleWebApp.FunctionalTests/target
  FunctionalTests: 
    name: Run Functional tests
    needs: [build]
    runs-on: windows-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    # Downloading test artifact
    - name: Download test Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: testartifacts
        path: testartifacts
    - name: run cmd
      run: |
        ls
        cd testartifacts
        ls
      # Run functional tests
    - name: set up test environment and run tests
      shell: pwsh
      run: .\testartifacts\scripts\prepareAndRunFunctionTests.ps1
