name: Build and deploy Docker app to Azure
on:
  push:
    branches:
      - master

env:
  APPNAME: javascript4test-anand
  APPLICATIONPATH: Application
  HOSTINGPLAN: javascript4test-anand
  DOCKERFILEPATH: "Application"
  REGISTRYSKU: "Standard"
  REGISTRYNAME: "javascript4testanandacr"
  REGISTRYLOCATION: "South Central US"
  IMAGENAME: "javascript4testanandc093"
  RESOURCEGROUPNAME: javascript4test-anand-rg
  LOCATION: South Central US
  APPINSIGHTSLOCATION: South Central US
  SUBSCRIPTIONID: 7489b9b9-8abe-4b02-a0d9-f09f368df55f
  SKU: S1 Standard
  JAVA_VERSION: 1.8

jobs:
  FunctionalTests: 
    name: Run Functional tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: set up test environment and run tests
      shell: pwsh
      run: .\Application\scripts\prepareAndRunFunctionTests.ps1
